version: 2
jobs:
    test:
        machine:
            enabled: true
            image: circleci/classic
        steps:
            - checkout
            - run: docker pull $APP_DOCKER_IMAGE_NAME
            - run: docker run --rm -it -v $(pwd):/app $APP_DOCKER_IMAGE_NAME /usr/local/bin/composer install -n --prefer-dist
            - run: docker run --rm -it -v $(pwd):/app $APP_DOCKER_IMAGE_NAME "./cs"

    deploy:
        working_directory: ~/julianli
        docker:
            - image: ansible/ansible:ubuntu1604
              environment:
                  ANSIBLE_HOST_KEY_CHECKING: no
        steps:
            - run:
                name: Install System Packages
                command: pip install --upgrade pip & pip install ansible
            - checkout
            - restore_cache:
                key: julianli-{{ .Branch }}-{{ checksum "./ansible/requirements.yml" }}-v1
            - run: ansible-galaxy install -r ansible/requirements.yml
            - save_cache:
                key: julianli-{{ .Branch }}-{{ checksum "./ansible/requirements.yml" }}-v1
                paths:
                    - "./root/.ansible/roles"

            - run: echo $ANSIBLE_VAULT_PASS > ./ansible/.vault-pass.txt
            - run: ansible-playbook ansible/deploy.yml -i ansible/hosts.ini --vault-password-file=./ansible/.vault-pass.txt
            - run: rm ./ansible/.vault-pass.txt

workflows:
    version: 2
    test_deploy:
        jobs:
            - test:
                filters:
                    branches:
                        ignore:
                            - master
            - deploy:
                filters:
                    branches:
                        only: master
