database_url: "{{ vault_database_url }}"
mailer_url: "{{ vault_mailer_url }}"
mailer_host_email: "{{ vault_mailer_host_email }}"
mailer_admin_email: "{{ vault_mailer_admin_email }}"
aws_s3_key: "{{ vault_aws_key }}"
aws_s3_secret: "{{ vault_aws_secret }}"
aws_s3_region: "{{ vault_aws_region }}"